# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replit/goval/api/features/features.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(replit/goval/api/features/features.proto\x12\x19replit.goval.api.features\"\x05\n\x03Gpu\"\t\n\x07\x42oosted\"\x8c\x01\n\x07\x46\x65\x61ture\x12-\n\x03gpu\x18\x01 \x01(\x0b\x32\x1e.replit.goval.api.features.GpuH\x00\x12\x35\n\x07\x62oosted\x18\x02 \x01(\x0b\x32\".replit.goval.api.features.BoostedH\x00\x12\x10\n\x08required\x18\x03 \x01(\x08\x42\t\n\x07\x66\x65\x61tureB&Z$github.com/replit/goval/api/featuresb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replit.goval.api.features.features_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/replit/goval/api/features'
  _globals['_GPU']._serialized_start=71
  _globals['_GPU']._serialized_end=76
  _globals['_BOOSTED']._serialized_start=78
  _globals['_BOOSTED']._serialized_end=87
  _globals['_FEATURE']._serialized_start=90
  _globals['_FEATURE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
