# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replit/goval/api/repl/repl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from replit.goval.api.features import features_pb2 as replit_dot_goval_dot_api_dot_features_dot_features__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n replit/goval/api/repl/repl.proto\x12\x15replit.goval.api.repl\x1a(replit/goval/api/features/features.proto\"v\n\x04Repl\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x03 \x01(\t\x12\x0c\n\x04slug\x18\x04 \x01(\t\x12\x0c\n\x04user\x18\x05 \x01(\t\x12\x12\n\nsourceRepl\x18\x06 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x07 \x01(\t\"\xfb\x01\n\x0eResourceLimits\x12\x0b\n\x03net\x18\x01 \x01(\x08\x12\x0e\n\x06memory\x18\x02 \x01(\x03\x12\x0f\n\x07threads\x18\x03 \x01(\x01\x12\x0e\n\x06shares\x18\x04 \x01(\x01\x12\x0c\n\x04\x64isk\x18\x05 \x01(\x03\x12@\n\x05\x63\x61\x63he\x18\x06 \x01(\x0e\x32\x31.replit.goval.api.repl.ResourceLimits.Cachability\x12\x17\n\x0frestrictNetwork\x18\x07 \x01(\x08\x12\x15\n\rpreventWakeup\x18\x08 \x01(\x08\"+\n\x0b\x43\x61\x63hability\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04USER\x10\x01\x12\x08\n\x04REPL\x10\x02\"%\n\x0bPermissions\x12\x16\n\x0etoggleAlwaysOn\x18\x01 \x01(\x08\"\xab\x02\n\x08Metadata\x12)\n\x04repl\x18\x07 \x01(\x0b\x32\x1b.replit.goval.api.repl.Repl\x12=\n\x0eresourceLimits\x18\n \x01(\x0b\x32%.replit.goval.api.repl.ResourceLimits\x12\x37\n\x0bpersistence\x18\x06 \x01(\x0e\x32\".replit.goval.api.repl.Persistence\x12\r\n\x05\x66lags\x18\x0e \x03(\t\x12\x37\n\x0bpermissions\x18\x0f \x01(\x0b\x32\".replit.goval.api.repl.Permissions\x12\x34\n\x08\x66\x65\x61tures\x18\x10 \x03(\x0b\x32\".replit.goval.api.features.Feature*6\n\x0bPersistence\x12\x0e\n\nPERSISTENT\x10\x00\x12\r\n\tEPHEMERAL\x10\x01\x12\x08\n\x04NONE\x10\x02\x42\"Z github.com/replit/goval/api/replb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replit.goval.api.repl.repl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z github.com/replit/goval/api/repl'
  _PERSISTENCE._serialized_start=816
  _PERSISTENCE._serialized_end=870
  _REPL._serialized_start=101
  _REPL._serialized_end=219
  _RESOURCELIMITS._serialized_start=222
  _RESOURCELIMITS._serialized_end=473
  _RESOURCELIMITS_CACHABILITY._serialized_start=430
  _RESOURCELIMITS_CACHABILITY._serialized_end=473
  _PERMISSIONS._serialized_start=475
  _PERMISSIONS._serialized_end=512
  _METADATA._serialized_start=515
  _METADATA._serialized_end=814
# @@protoc_insertion_point(module_scope)
